version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          TZ: Asia/Tokyo
          RAILS_ENV: test
      - image: circleci/mysql:5.7.22
        environment:
          TZ: Asia/Tokyo
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_ROOT_HOST: "%"
      - image: redis:4.0.9

    working_directory: ~/todo-api-rails-sample

    parallelism: 1

    steps:
      - checkout

      # Update Node.js and npm
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.13.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v

      # bundle install
      - restore_cache:
          key: todo-api-rails-sample-gem-{{ checksum "Gemfile.lock" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: todo-api-rails-sample-gem-{{ checksum "Gemfile.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - ./vendor/bundle

      # yarn install
      - restore_cache:
          key: todo-api-rails-sample-node-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: yarn install
          command: yarn install --ignore-engines
      - save_cache:
          key: todo-api-rails-sample-node-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - ./node_modules

      # setup config
      - run:
          name: setup .env
          command: cp .env.circleci .env

      # setup database
      - run:
          name: setup database
          command: bundle exec rails db:setup

      # run rspec
      - run:
          name: rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out tmp/test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # run rubocop
      - run:
          name: rubocop
          command: bundle exec rubocop --parallel

      # run slim-lint
      - run:
          name: slim-lint
          command: bundle exec slim-lint app/views/*

      # run scss-lint
      - run:
          name: scss-lint
          command: bundle exec scss-lint

      # store_test_results
      - store_test_results:
          path: tmp/test_results
